name = "icaidiet-backend"
main = "src/index.ts"
compatibility_date = "2024-12-24"
account_id = "e2d253a3ec0b14fada1430019e8373a6"

# Bind a D1 database.
[[d1_databases]]
binding = "DB"
database_name = "icaidiet_text_records"
database_id = "cb3b2de8-fdc6-4bd3-81c5-668c22f494fd"
migrations_dir = "migrations"

# Bind an R2 Bucket
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "icaidietpdfs"
